// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    Layout: typeof import('./src/layout/Layout.vue')['default']
    NavBar: typeof import('./src/layout/NavBar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RiArticleLine: typeof import('~icons/ri/article-line')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}

export { }
